### ISSUE TITLE
Support for Switchbot Blind Tilt?

### ISSUE THREAD

**Issue by tasi333** [jbasen/Crestron-SwitchBot#1]
Hello, could you please add support for the Blind Tilt product?

Thanks.

**Comment by jbasen** [comment]
I will take a look at that.  I'm in the middle of an update to my Crestron-Hubitat code so it may take a some time.

**Comment by jbasen** [comment]
hi @tasi333 

I apologize that this has taken so long.  Things have just been very hectic.  I have added the code to support the blind tilt.  I haven't had the time yet to test it but if you want to give it a try here is a link that you can download a new version of the demo program that includes a module for the Blind Tilt.  The supported commands are open, close up, close down, and set the position.

https://1drv.ms/u/s!AjlldUMTB6AFgoJUkE05rvrYuOlZSg?e=MrbXhz

Enjoy and let me know how things go.  

Thanks for your patience.

**Comment by jbasen** [comment]
v5 of the switchbot driver has been uploaded and supports the blind tilt
